apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: mysql
 name: mysql
 namespace: flask-datastore
spec:
 replicas: 1
 selector:
   matchLabels:
     deployment: mysql
 template:
   metadata:
     labels:
       deployment: mysql
   spec:
     containers:
       - image: registry.hub.docker.com/library/mysql
         imagePullPolicy: IfNotPresent
         name: mysql
         ports:
          - containerPort: 3306
         env:
          - name: MYSQL_ROOT_PASSWORD
            value: "password"
         volumeMounts:
          - name: setup-volume
            mountPath: /docker-entrypoint-initdb.d/schema.sql
            subPath: schema.sql
         # pod security
         securityContext:
           allowPrivilegeEscalation: false
           capabilities:
             drop: ["ALL"]
           runAsNonRoot: true
           seccompProfile:
             type: RuntimeDefault
     volumes:
       - name: setup-volume
         configMap:
           name: mysql-configmap
