apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: mysql
# uncomment if needed
#   app.kubernetes.io/component: demo
#   app.kubernetes.io/instance: demo
 name: mysql
 namespace: flask-datastore
spec:
 # securityContext:
 #   allowPrivilegeEscalation: false
 replicas: 1
 selector:
   matchLabels:
     deployment: mysql
 template:
   metadata:
     labels:
       deployment: mysql
   spec:
     containers:
       - image: quay.io/rh-ee-jbrawley/mysql-demo:fa14cba
         imagePullPolicy: IfNotPresent
         name: mysql
         env:
          - name: MYSQL_ROOT_PASSWORD
            value: "password"
         #command: ["/bin/sh", "-c", "mysql", "-uroot", "-ppassword", "<", "\"setup.sql\""]
         #lifecycle:
         #   postStart:
         #      exec:
         #         command: ["/bin/sh", "-c", "mysql", "-uroot", "-ppassword", "<", "\"setup.sql\""]
         #ports:
         #  - containerPort: 5000
         # fix pod security
         securityContext:
           allowPrivilegeEscalation: false
           capabilities:
             drop: ["ALL"]
           runAsNonRoot: true
           seccompProfile:
             type: RuntimeDefault
