apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: demo
# uncomment if needed
#   app.kubernetes.io/component: demo
#   app.kubernetes.io/instance: demo
 name: demo
 namespace: flask-demo
spec:
 replicas: 2
 selector:
   matchLabels:
     deployment: demo
 template:
   metadata:
     labels:
       deployment: demo
   spec:
     containers:
       - image: quay.io/repository/rh-ee-jbrawley/flask-demo:3ed1e2b
         imagePullPolicy: Always
         name: demo
         ports:
           - containerPort: 5000
